project:
  type: book

book:
  title: "Lamalab Tool and Paper Notes"
  author: "LamaLab"
  date: "4/11/2024"
  chapters:
    - index.qmd
    - part: Tools
      chapters:
        - tools/hydra.qmd
        - tools/ip_rotator.qmd
        - tools/polars.qmd
        - tools/thunder_client.qmd
        - tools/tmux.qmd
        - tools/trimean.ipynb
        - tools/pandarallel.ipynb
        - tools/bfg.qmd
        - tools/showyourwork.qmd
    - part: Papers
      chapters:
        - papers/jiaxing_llm4mat.qmd
        - papers/chem_yield_prediction_2024.md

bibliography: references.bib
# csl: nature.csl

format:
  html:
    theme: cosmo
    number-sections: false
  pdf:
    documentclass: scrreprt


